#####
#
#  TIME DOMAIN REDUCTION SETTINGS
#
#  Set parameters here that organize how your full timeseries
#   data will be divided into representative period clusters.
#   Ensure that time_domain_reduction is set to 1 in GenX_settings.yml
#   before running. Run within GenX or use PreCluster.jl to test and
#   examine representative period output before proceeding.
#   Specify your data input directory as inpath within Run_test.jl
#   or PreCluster.jl.
#
#####

  #   - TimestepsPerRepPeriod
  #   Typically 168 timesteps (e.g., hours) per period, this designates
  #   the length of each representative period.
TimestepsPerRepPeriod: 168

  #   - ClusterMethod
  #   Either 'kmeans' or 'kmedoids', this designates the method used to cluster
  #   periods and determine each point's representative period.
ClusterMethod: 'kmeans'

  #   - ScalingMethod
  #   Either 'N' or 'S', this designates directs the module to normalize ([0,1])
  #   or standardize (mean 0, variance 1) the input data.
ScalingMethod: "S"

  #   - MaxPeriods
  #   The maximum number of periods - both clustered periods and extreme periods -
  #   that may be used to represent the input data. If IterativelyAddPeriods is on and the
  #   error threshold is never met, this will be the total number of periods.
MaxPeriods: 4
MinPeriods: 4
IterativelyAddPeriods: 1
IterateMethod: "cluster"
Threshold: 0.05
nReps: 100
LoadWeight: 1
WeightTotal: 8736
ClusterFuelPrices: 0
UseExtremePeriods: 1
ExtremePeriods:
  Wind:
    System:
      Absolute:
        Min: 0
        Max: 0
      Integral:
        Min: 1
        Max: 0
    Zone:
      Absolute:
        Min: 0
        Max: 0
      Integral:
        Min: 0
        Max: 0
  Load:
    System:
      Absolute:
        Min: 0
        Max: 1
      Integral:
        Min: 0
        Max: 0
    Zone:
      Absolute:
        Min: 0
        Max: 0
      Integral:
        Min: 0
        Max: 0
  PV:
    System:
      Absolute:
        Min: 0
        Max: 0
      Integral:
        Min: 1
        Max: 0
    Zone:
      Absolute:
        Min: 0
        Max: 0
      Integral:
        Min: 0
        Max: 0